version: '2.1'
services:
  ftp:
    image: delfer/alpine-ftp-server
    network_mode: host
#    ports:
#      - 21:21
#      - 21000-21010:21000-21010
    environment:
      - USERS=valbury|P@ssw0rd1!|/home/valbury|10001 admin|P@ssw0rd1!|/home/admin|10002
    volumes:
      - ./valbury:/home/valbury
      - ./admin:/home/admin